language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

jobs:
  include:
    - stage: test
      script:
        - python vochabular/manage.py migrate
        - python vochabular/manage.py test
    - stage: lint
      script:
        - cd vochabular
        - pylint --load-plugins pylint_django api vochabular --disable=C,W,R
    - stage: mypy
      script:
        - mypy vochabular