language: python
python:
  - "3.6"
install:
  - pip install -r requirements.txt

addons:
  postgresql: "9.4"
services:
  - postgresql

jobs:
  include:
    - stage: deps
      script:
        - pip install pip-tools && pip-compile -q & git diff --exit-code
    - stage: test
      script:
        - python vochabular/manage.py migrate
        - python vochabular/manage.py test
    - stage: lint
      script:
        - cd vochabular && DJANGO_SETTINGS_MODULE=vochabular.settings pylint --load-plugins pylint_django api vochabular --disable=C,W,R
    # - stage: mypy
    #   script:
    #     - mypy vochabular
