version: "3"

volumes:
  db_data:
services:
  db:
    image: postgres
    container_name: vocha_admin_db
    environment:
      POSTGRES_HOST_AUTH_METHOD: "trust"
    volumes:
      - db_data:/var/lib/postgresql/data
  backend:
    container_name: vocha_admin_backend
    build: .
    volumes:
      - ./vochabular:/code
      - ./scripts:/code/scripts
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      DB_HOST: "db"
  hasura:
    container_name: vocha_admin_hasura
    # Note the "special" image .cli-migrations which auto-applies pending migrations on startup
    image: hasura/graphql-engine:v1.3.1.cli-migrations-v2
    ports:
      - "8080:8080"
    volumes:
      # To enable "auto-migrations" for meta data and db changes
      - ./hasura/metadata:/hasura-metadata
      # Disable db migrations: Since this is Django's job, we want to disable automatic migrations
      # - ./hasura/migrations:/hasura-migrations
    depends_on:
      - "db"
    restart: always
    environment:
      # Used for remote schema stitching
      DJANGO_URL: http://backend:8000/api
      HASURA_GRAPHQL_DATABASE_URL: postgres://postgres@db:5432/postgres
      HASURA_GRAPHQL_ENABLE_CONSOLE: "true" # set to "false" to disable console
      HASURA_GRAPHQL_ENABLED_LOG_TYPES: startup, http-log, webhook-log, websocket-log, query-log
      HASURA_GRAPHQL_JWT_SECRET: '{"type": "RS512", "key": "-----BEGIN CERTIFICATE-----\nMIIDFTCCAf2gAwIBAgIJPfoA7M4Opdl5MA0GCSqGSIb3DQEBCwUAMCgxJjAkBgNV\nBAMTHXZvY2hhYnVsYXItYWRtaW4uZXUuYXV0aDAuY29tMB4XDTE5MDExNTIyNTUw\nNFoXDTMyMDkyMzIyNTUwNFowKDEmMCQGA1UEAxMddm9jaGFidWxhci1hZG1pbi5l\ndS5hdXRoMC5jb20wggEiMA0GCSqGSIb3DQEBAQUAA4IBDwAwggEKAoIBAQCfE+zs\nqqpZcsEOqTPCFnPDsQzJqF04y5dOmxe7Z1pJA14WtcqYe+3dOcFQ2avuB/qROBDZ\n2LOMRS3W/T9tyCuj0L3b1lCeNm8F7vptPU+pzURmz5Gj6lDK5BXdpBUIoj8D172i\nM2Xd1QycnIWmVCAyG+Hwx7h8W1cCMNhOBGozRooNilWOXvxIard7Cxib3NDmHn37\nX9lCNws/nP3Pi9bnOSVJ+htP/J6zlTxZDyZ/zU2ZGMgEUFf6BSXooPJFoIbffusv\nn17IGVieuJfBSWgsLyw2vZUEDbsQZCtXI1c1lJwdHtZ2VQZEAKSBU5CcAMSg7ynZ\nqp0eTkMIeNGOdFfjAgMBAAGjQjBAMA8GA1UdEwEB/wQFMAMBAf8wHQYDVR0OBBYE\nFEs4OTeXKUQHe4BSEA5NmCLfGxGYMA4GA1UdDwEB/wQEAwIChDANBgkqhkiG9w0B\nAQsFAAOCAQEAKCi2SdX6eYAmrIXtPCYVUzZAzVvSFL4+1ZIRHTCa6Og/2pfYZejy\naUUzxgi3Po2PmZtRih42z7vPzYG14g3v3sm9RhguwyYymvpMnKvT5jBq3szMXyRF\n9gmoElttqEcCHdDOta758JpI2Zkh+kkJwnaLHMk560sYyQc1PHi7+k/7vf+pf7n4\njVZHPqRUWggXdZ7fF55Lt/POo9aDCQ3u7hjQaNypdM7hzbrWcxPVFo8f/l136ZsQ\n8bph1UUK3oF0l1UsJW8bM05Wre1aqjwegQaYRgOHORk+Iwql5T6YpFrZ5gqytqRd\nEp0IsOkadEvykWjW8PgnatbZVG7p1kwjTg==\n-----END CERTIFICATE-----"}'
      HASURA_GRAPHQL_ADMIN_SECRET: myadminsecretkey
