version: '3'

services:
  db:
    image: postgres
    container_name: vocha_admin_db
  backend:
    container_name: vocha_admin_backend
    build: .
    volumes:
      - ./vochabular:/code
    ports:
      - "8000:8000"
    depends_on:
      - db