# Generated by Django 2.1.10 on 2019-07-28 12:25

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('titleCH', models.CharField(max_length=100, unique=True)),
                ('titleDE', models.CharField(max_length=100, unique=True)),
                ('description', models.CharField(max_length=500)),
                ('number', models.IntegerField()),
                ('fk_belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=500)),
                ('active', models.BooleanField()),
                ('context', models.CharField(blank=True, choices=[('A', 'Approver'), ('C', 'ContentCreator'), ('T', 'Translator'), ('I', 'Illustrator')], max_length=1, null=True)),
                ('written', models.DateTimeField(blank=True, default=datetime.datetime.now, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('data', models.TextField(max_length=500)),
                ('state', models.CharField(choices=[('C', 'creation'), ('R', 'in review'), ('U', 'to be updated'), ('T', 'to be translated'), ('F', 'final')], default='0', max_length=1)),
                ('locked_ts', models.DateTimeField(auto_now=True)),
                ('fk_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
                ('fk_component', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=45)),
                ('schema', models.TextField(max_length=100)),
                ('base', models.BooleanField(default=False)),
                ('icon', models.CharField(max_length=100)),
                ('label', models.CharField(max_length=45)),
                ('fk_parent_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ComponentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Media',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('type', models.CharField(max_length=45)),
                ('url', models.CharField(max_length=255)),
                ('fk_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('firstname', models.CharField(max_length=100)),
                ('lastname', models.CharField(max_length=100)),
                ('roles', models.CharField(max_length=120)),
                ('current_role', models.CharField(max_length=30)),
                ('language', models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2)),
                ('translator_languages', models.CharField(max_length=200)),
                ('event_notifications', models.BooleanField(default=True)),
                ('setup_completed', models.BooleanField(default=False)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('translatable', models.BooleanField()),
                ('fk_component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text_field', models.CharField(max_length=45)),
                ('valid', models.BooleanField()),
                ('fk_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('fk_text', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title_ch', models.CharField(blank=True, max_length=200)),
                ('title_de', models.CharField(blank=True, max_length=200)),
                ('fk_chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
                ('words', models.ManyToManyField(to='api.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=40)),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('example_sentence', models.CharField(blank=True, max_length=500, null=True)),
                ('fk_language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='text',
            name='master_translation',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Translation'),
        ),
        migrations.AddField(
            model_name='component',
            name='fk_component_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ComponentType'),
        ),
        migrations.AddField(
            model_name='component',
            name='fk_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component'),
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_parent_comment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
        migrations.AddField(
            model_name='chapter',
            name='languages',
            field=models.ManyToManyField(to='api.Language'),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('fk_language', 'fk_text')},
        ),
        migrations.AlterUniqueTogether(
            name='chapter',
            unique_together={('titleDE', 'number')},
        ),
    ]
