# Generated by Django 2.1.5 on 2019-02-27 17:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chapter',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('belongs_to', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.TextField(max_length=500)),
                ('active', models.BooleanField()),
            ],
        ),
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('data', models.TextField(max_length=500)),
                ('state', models.CharField(choices=[('C', 'creation'), ('R', 'in review'), ('U', 'to be updated'), ('T', 'to be translated'), ('F', 'final')], default='0', max_length=1)),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=45)),
                ('schema', models.TextField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Text',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('translatable', models.BooleanField()),
                ('master_translation', models.IntegerField()),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component')),
            ],
        ),
        migrations.CreateModel(
            name='Translation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(max_length=45)),
                ('text', models.CharField(max_length=45)),
                ('valid', models.BooleanField()),
                ('text_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Text')),
            ],
        ),
        migrations.CreateModel(
            name='Word',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='WordAR',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordCH',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordDE',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordEN',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordFA',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=40)),
                ('word', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
        ),
        migrations.CreateModel(
            name='WordGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chapter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Chapter')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='word',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Word'),
        ),
        migrations.AddField(
            model_name='member',
            name='word_group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WordGroup'),
        ),
        migrations.AddField(
            model_name='component',
            name='componentType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.ComponentType'),
        ),
        migrations.AddField(
            model_name='comment',
            name='component',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Component'),
        ),
    ]
