# Generated by Django 2.1.7 on 2019-03-30 13:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='component',
            old_name='fk_componentType',
            new_name='fk_component_type',
        ),
    ]
