# Generated by Django 2.1.10 on 2019-07-28 14:42

from django.db import migrations, models

def getTimestampSQL():
    f = open("scripts/timestamp.sql","r") 
    return f.read()

def getUUIDSQL():
    f = open("scripts/uuid.sql","r") 
    return f.read()

class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190728_1403'),
    ]

    operations = [
        migrations.RunSQL(getTimestampSQL()),
        migrations.RunSQL(getUUIDSQL()),
        migrations.RunSQL("select 'hello world' from __alter_uuid_default();"),
        migrations.RunSQL("select 'hello world' from __set_all_created_triggers();"),
        migrations.RunSQL("select 'hello world' from __set_all_modified_triggers();"),
    ]
