# Generated by Django 2.1.10 on 2019-07-28 14:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20190728_1403'),
    ]

    operations = [
        migrations.RunSQL("select 'hello world' from __alter_uuid_default();")
        migrations.RunSQL("select 'hello world' from __set_creation_date();")
        migrations.RunSQL("select 'hello world' from __set_modified_date();")
    ]
