# Generated by Django 2.1.11 on 2019-08-08 15:11

from django.db import migrations, models


def getOrderedList(payload):
    if not isinstance(payload, list):
        raise ValueError("No valid array passed as payload!")
    f = open("scripts/ordered_list.sql", "r")
    content = f.read()
    return content.replace('__PLACEHOLDER_ORDERED_COLUMN_ARRAY__', '[ ' + ','.join(payload) + ' ]')


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190728_1442'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='order_in_chapter',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.RunSQL(getOrderedList(payload=[
                          'api_component', 'order_in_chapter', 'fk_chapter_id', 'fk_component_id'])),
        migrations.RunSQL(
            "select 'HELLO' from __set_all_ordered_list_triggers();")
    ]
