# Generated by Django 2.1.10 on 2019-11-23 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20191123_1208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='text',
            name='master_translation',
        ),
        migrations.AddField(
            model_name='text',
            name='placeholder',
            field=models.TextField(null=True),
        ),
    ]
