# Generated by Django 2.1.7 on 2019-04-13 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20190330_1553'),
    ]

    operations = [
        migrations.AddField(
            model_name='wordgroup',
            name='title_ch',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='title_de',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AlterField(
            model_name='wordar',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordar',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wordch',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordch',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wordde',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordde',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='worden',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='worden',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='wordfa',
            name='audio',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='wordfa',
            name='example_sentence',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
