# Generated by Django 2.1.7 on 2019-04-13 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20190413_1452'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='member',
            name='fk_word',
        ),
        migrations.RemoveField(
            model_name='member',
            name='fk_word_group',
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='words',
            field=models.ManyToManyField(to='api.Word'),
        ),
        migrations.DeleteModel(
            name='Member',
        ),
    ]
