# Generated by Django 2.1.10 on 2019-10-28 20:21

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_auto_20191028_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
