# Generated by Django 2.1.10 on 2019-10-28 20:24

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20191028_2021'),
    ]

    operations = [
        migrations.AlterField(
            model_name='componenttype',
            name='schema',
            field=django.contrib.postgres.fields.jsonb.JSONField(),
        ),
    ]
