# Generated by Django 2.1.7 on 2019-05-30 10:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_auto_20190413_1540'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='base',
            field=models.BooleanField(default=False),
        ),
    ]
