# Generated by Django 2.1.7 on 2019-05-30 12:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_componenttype_root'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='fk_parent_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='api.ComponentType'),
        ),
        migrations.AddField(
            model_name='componenttype',
            name='icon',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='componenttype',
            name='label',
            field=models.CharField(default='', max_length=45),
            preserve_default=False,
        ),
    ]
