# Generated by Django 3.0.3 on 2020-04-04 16:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_auto_20200403_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='disable_children',
            field=models.BooleanField(default=False),
        ),
    ]
