# Generated by Django 2.1.10 on 2019-10-28 20:47

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_auto_20191028_2029'),
    ]

    operations = [
        migrations.CreateModel(
            name='Character',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('formal_name', models.CharField(max_length=45)),
                ('informal_name', models.CharField(max_length=45)),
                ('gender', models.CharField(choices=[('f', 'Female'), ('m', 'Male')], default='f', max_length=1, null=True)),
                ('title', models.CharField(max_length=45, null=True)),
                ('speaker', models.CharField(max_length=45, null=True)),
                ('fk_book', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Book')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='character',
            unique_together={('informal_name', 'fk_book'), ('formal_name', 'fk_book')},
        ),
    ]
