# Generated by Django 2.1.10 on 2019-10-28 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_auto_20191028_2047'),
    ]

    operations = [
        migrations.AddField(
            model_name='componenttype',
            name='fk_frontend_widget',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='frontend_widget', to='api.ComponentType'),
        ),
        migrations.AlterField(
            model_name='wordgroup',
            name='fk_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Chapter'),
        ),
    ]
