# Generated by Django 2.1.7 on 2019-05-30 15:46

from django.db import migrations, models
from api.models import Chapter


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190530_1546'),
    ]

    def insert_titles(apps, schema_editor):
        for row in Chapter.objects.all():
            row.titleDE = row.titleDE + " - " + str(row.number)
            row.titleCH = row.titleDE + " - " + str(row.number)
            row.save()

    operations = [
        migrations.RunPython(insert_titles),
        migrations.AlterField(
            model_name='chapter',
            name='titleCH',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='titleDE',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
