# Generated by Django 2.1.7 on 2019-05-30 15:46

from django.db import migrations, models
from api.models import Chapter


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0009_auto_20190530_1546'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chapter',
            name='titleCH',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='chapter',
            name='titleDE',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
