# Generated by Django 2.1.7 on 2019-05-30 17:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('api', '0010_auto_20190530_1546'),
    ]

    operations = [
        migrations.AddField(
            model_name='component',
            name='fk_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='component',
            name='locked_ts',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
