# Generated by Django 2.1.10 on 2019-11-23 09:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_auto_20191123_0933'),
    ]

    operations = [
        migrations.RenameField(
            model_name='language',
            old_name='code',
            new_name='id',
        ),
        migrations.AlterField(
            model_name='translation',
            name='fk_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language', to_field='id'),
        ),
        migrations.AlterField(
            model_name='wordtranslation',
            name='fk_language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language', to_field='id'),
        ),
    ]
