# Generated by Django 2.1.7 on 2019-05-31 08:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0012_auto_20190530_1742'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='comment',
            new_name='text',
        ),
        migrations.RemoveField(
            model_name='comment',
            name='fk_text',
        ),
        migrations.AddField(
            model_name='comment',
            name='context',
            field=models.CharField(blank=True, choices=[('A', 'Approver'), ('C', 'ContentCreator'), ('T', 'Translator'), ('I', 'Illustrator')], max_length=1, null=True),
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_component',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Component'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='comment',
            name='fk_parent_comment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='api.Comment'),
        ),
    ]
