# Generated by Django 2.1.10 on 2019-11-23 10:19

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0013_auto_20191123_1001'),
    ]

    operations = [
        migrations.CreateModel(
            name='WordGroupTitle',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('title', models.CharField(max_length=200)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='wordgroup',
            name='title_ch',
        ),
        migrations.RemoveField(
            model_name='wordgroup',
            name='title_de',
        ),
        migrations.AddField(
            model_name='wordgrouptitle',
            name='wordGroup',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.WordGroup'),
        ),
        migrations.AddField(
            model_name='wordgroup',
            name='titles',
            field=models.ManyToManyField(through='api.WordGroupTitle', to='api.Language'),
        ),
    ]
