# Generated by Django 2.1.7 on 2019-05-31 12:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190531_1254'),
    ]

    operations = [
        migrations.AlterField(
            model_name='component',
            name='fk_locked_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Profile'),
        ),
    ]
