# Generated by Django 2.1.7 on 2019-07-13 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0014_auto_20190531_1118'),
        ('api', '0015_auto_20190531_1257'),
    ]

    operations = [
    ]
