# Generated by Django 2.1.7 on 2019-07-13 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_merge_20190713_0837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('de', 'Deutsch'), ('en', 'English')], default=('de', 'Deutsch'), max_length=2),
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('language', 'fk_text')},
        ),
    ]
