# Generated by Django 2.1.10 on 2019-11-23 10:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0016_auto_20191123_1027'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='fk_chapter',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='api.Chapter'),
        ),
    ]
