# Generated by Django 2.1.10 on 2019-07-28 09:51

from django.db import migrations, models
import django.db.models.deletion
from api.models import Language


LANGUAGES = [
    ["de", "Deutsch"],
    ["ch", "Schweizerdeutsch"],
    ["en", "Englisch"],
    ["ar", "Arabisch"],
    ["fa", "Farsi"]
]


def insertLanguages(apps, schema_editor):
    for lang in LANGUAGES:
        language = Language(code=lang[0], name=lang[1])
        language.save()


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190713_1217'),
    ]

    operations = [
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(max_length=20)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RunPython(insertLanguages),
        migrations.CreateModel(
            name='WordTranslation',
            fields=[
                ('id', models.AutoField(auto_created=True,
                                        primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('text', models.CharField(max_length=40)),
                ('audio', models.CharField(blank=True, max_length=255, null=True)),
                ('example_sentence', models.CharField(
                    blank=True, max_length=500, null=True)),
                ('fk_language', models.ForeignKey(
                    on_delete=django.db.models.deletion.CASCADE, to='api.Language')),
                ('word', models.OneToOneField(
                    on_delete=django.db.models.deletion.CASCADE, to='api.Word')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.RemoveField(
            model_name='wordar',
            name='word',
        ),
        migrations.RemoveField(
            model_name='wordch',
            name='word',
        ),
        migrations.RemoveField(
            model_name='wordde',
            name='word',
        ),
        migrations.RemoveField(
            model_name='worden',
            name='word',
        ),
        migrations.RemoveField(
            model_name='wordfa',
            name='word',
        ),
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(
                choices=[('de', 'Deutsch'), ('en', 'English')], default='de', max_length=2),
        ),
        migrations.DeleteModel(
            name='WordAR',
        ),
        migrations.DeleteModel(
            name='WordCH',
        ),
        migrations.DeleteModel(
            name='WordDE',
        ),
        migrations.DeleteModel(
            name='WordEN',
        ),
        migrations.DeleteModel(
            name='WordFA',
        ),
        migrations.AddField(
            model_name='chapter',
            name='languages',
            field=models.ManyToManyField(to='api.Language'),
        ),
        migrations.AddField(
            model_name='translation',
            name='fk_language',
            field=models.ForeignKey(
                default=1, on_delete=django.db.models.deletion.CASCADE, to='api.Language'),
            preserve_default=False,
        ),
        migrations.AlterUniqueTogether(
            name='translation',
            unique_together={('fk_language', 'fk_text')},
        ),
    ]
