# Generated by Django 2.1.7 on 2019-07-13 13:13

import api.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0017_auto_20190713_1217'),
    ]

    operations = [
        migrations.AddField(
            model_name='chapter',
            name='languages',
            field=models.CharField(default='de,ch', max_length=50, validators=[api.models.validate_languages]),
        ),
    ]
