# Generated by Django 2.1.10 on 2019-07-28 10:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0018_auto_20190728_0951'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='translation',
            name='language',
        ),
    ]
